### ISSUE TITLE
Commande arrêt ne fonctionne pas

### ISSUE THREAD

**Issue by Alcyon71** [mika-nt28/Jeedom-reveil#115]
Bonjour,

La commande arrêt ne fonctionne pas chez moi.
Je suis loin d’être un pro en php, mais je me suis permit de jeter un œil.
Je me demande si le problème ne vient pas de $Listener dans la class reveilCmd.
`$Listener=cmd::byId(str_replace('#','',$this->getValue()));`
Car dans le cas d'une action 'stop' ou 'snooze' $Listener est vide donc switch n'est pas exécuté.

Merci

**Comment by mika-nt28** [comment]
Effectivement tu as bien mis je pense le doit sur le problème.
Je n'utilise pas cette fonction chez moi je ne l'ai pas vue
C'est bisare que personne ne m'est remonté se problème.
