### ISSUE TITLE
Impossible d'ajouter une condition d’exécution ou une action

### ISSUE THREAD

**Issue by Gis70** [mika-nt28/Jeedom-reveil#46]
Bonjour,

Il m'est impossible d'ajouter une condition d’exécution ou une action en cliquant sur les boutons Ajouter une condition dans "actions" ou "conditions d’exécution".

Je suis avec la dernière version stable du plugin et Jeedom v3.0.9.

**Comment by mika-nt28** [comment]
Effectivement il y avait un bug de ce coté la.
J'ai forcé la mise a jours

**Comment by Gis70** [comment]
Merci.

**Comment by Gis70** [comment]
Bonjour,

Il y a toujours un bug, en effet le pop up pour sélectionner un équipement ou condition s'affiche bien mais une fois sélectionné, cela ne s'écrit pas dans le champ.

De plus dans les actions même quand on a sélectionné libre, c'est la conf pour le simulateur d'aube qui s'affiche, il faut recliquer sur simulateur puis libre et là c'est bon il ne reste que le champ pour les actions.

**Comment by mika-nt28** [comment]
Effectivement je corrige ca pour demain

**Comment by Gis70** [comment]
Bonjour, la correction apporte le fonctionnement des actions, merci. J'ai trouvé ça comme petit bug encore : 
- Les paramètres d'une action et  (exemple d'envoi d'un mail) ne se mettent pas lors de la sélection de l'action, il faut cliquer sur sauvegarder pour voir apparaître le champ, et de plus le champ n'est pas en dessous de "paramètre" mais sous l'action
- Actions exécutées 2x
- Le CRON n'est pas retiré si on supprime l'équipement (si on le désactive il est bien retirer du moteur cron)

Merci pour les corrections.

**Comment by mika-nt28** [comment]
Peux tu ouvrir une issue pour chaque problème.
C'est plus simple a gérer

C'est normal qu'il les paramètre de l'action s'ouvre en dessous.
L'onglet paramètre c'est pour le paramétrage de fonction lier au plugin (pour l'instant uniquement la simulation d'aube

**Comment by Gis70** [comment]
OK. Je split.
