### ISSUE TITLE
CRON non supprimé lors de la suppression d'un équipement

### ISSUE THREAD

**Issue by Gis70** [mika-nt28/Jeedom-reveil#50]
Bonjour,

Le cron n'est pas supprimé si l'on supprime un équipement.

**Comment by mika-nt28** [comment]
Étrange il est pourtant bien supprimer dans le code.
Tu n’aurais pas un log dans http.error

**Comment by Gis70** [comment]
Je n'ai rien dans le http.error
L'équipement est bien supprimé de la DB je suis allé voir dans Mysql, mais le CRON est toujours dans la DB.

**Comment by mika-nt28** [comment]
J'ai passée la suppression des cron en preRemove() peut comme le cron fait appel a son id le postRemove peut posé problème.
La mise a jours sera dispo demain tien moi au courant

**Comment by Gis70** [comment]
C'est OK, j'ai remplacé le code in situ. Merci
